
environment:
    global:
        CYG_ROOT: C:\cygwin
        CYG_MIRROR: http://cygwin.mirror.constant.com
        CYG_CACHE: C:\cygwiin\var\cache\setup
        CYG_BASH: C:\cygwin\bin\bash

cache:
    - '%CYG_CACHE%'

clone_depth: 1

init:
    - git config --global core.autocrlf input

install:
    - ps: 'Start-FileDownload "http://cygwin.com/setup-x86.exe" -FileName "setup-x86.exe"'
    - 'setup-x86.exe --quiet-mode --no-shortcuts --only-site --root "%CYG_ROOT%" --site "%CYG_MIRROR%" --local-package-dir "%CYG_CACHE%" --packages automake,bison,gcc-core,libtool,make,gettext-devel,gettext,intltool,pkg-config,clang,llvm,libqt3-devel-3.3.8b-19,libqt3-3.3.8b-19,qt3-qtconfig-3.3.8b-19,qt3-devel-tools-3.3.8b-19,qt3-debuginfo-3.3.8b-19,qt3-doc-3.3.8b-19   > NUL 2>&1'
    - '%CYG_BASH% -lc "cygcheck -dc cygwin"'

build_script:
    - 'echo hello world'
    - '%CYG_BASH% -lc "echo \"hello from Cygwin\""'
    # - '%CYG_BASH% -lc "./configure"'
    # - '%CYG_BASH% -lc "make"'
    - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; qmake -project && qmake && make"'    

test: off

branches:
    only:
        - master
